use serde::{Deserialize, Serialize};

use super::Ecosystem;
use crate::model::Ecosystem::{
    AnsibleGalaxy, Bazel, Cargo, CocoaPods, Composer, Conan, Cpan, Cpp, Cran, Deno, Docker, Dotnet,
    Dub, Go, Hackage, Haxelib, Helm, Hex, Julia, LuaRocks, Maven, Nim, Nix, Npm,
    Opam as OpamEcosystem, Pub, Python, Ruby, Swift, Terraform, Unity, Vcpkg, Zig,
};
use crate::model::ManifestKind::{
    AnsibleGalaxyRequirementsYaml, BazelModule, BazelWorkspace, Cabal, CabalProject, CargoToml,
    ClojureDepsEdn, Cmake, CocoaPodsPodfile, ComposerJson, ConanfilePy, ConanfileTxt, Cpanfile,
    DenoImportMapJson, DenoJson, DockerComposeYaml, Dockerfile, DotnetProjectJson, DotnetXml,
    DubJson, DubSdl, DuneProject, Gemfile, GleamToml, GoMod, GradleBuild, GradleSettings,
    GradleVersionCatalogToml, HaxelibJson, HelmChartYaml, JsrJson, JuliaManifestToml,
    JuliaProjectToml, KustomizationYaml, LeiningenProjectClj, LuaRockspec, MavenPomXml, MesonWrap,
    MixExs, Nimble, NixFlake, NpmPackageJson, NpmPackageJson5, NpmPackageYaml, Opam,
    PaketDependencies, PaketReferences, PnpmYaml, PubspecOverridesYaml, PubspecYaml, PythonPipfile,
    PythonPyprojectToml, PythonRequirementsTxt, RDescription, RebarConfig, RenvLock, RubyGemspec,
    SbtBuild, StackYaml, SwiftPackage, TerraformTf, UnityProjectManifestJson, VcpkgJson, XmakeLua,
    ZigBuildZon,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ManifestKind {
    CargoToml,
    ComposerJson,
    DenoJson,
    DenoImportMapJson,
    JsrJson,
    DotnetProjectJson,
    DotnetXml,
    PaketDependencies,
    PaketReferences,
    DockerComposeYaml,
    Dockerfile,
    KustomizationYaml,
    DubJson,
    DubSdl,
    Gemfile,
    RubyGemspec,
    GoMod,
    MavenPomXml,
    GradleBuild,
    GradleSettings,
    GradleVersionCatalogToml,
    SbtBuild,
    ClojureDepsEdn,
    LeiningenProjectClj,
    MixExs,
    RebarConfig,
    GleamToml,
    Opam,
    DuneProject,
    Cabal,
    CabalProject,
    StackYaml,
    JuliaProjectToml,
    JuliaManifestToml,
    RDescription,
    RenvLock,
    ConanfileTxt,
    ConanfilePy,
    VcpkgJson,
    Cmake,
    XmakeLua,
    MesonWrap,
    BazelWorkspace,
    SwiftPackage,
    ZigBuildZon,
    Nimble,
    LuaRockspec,
    Cpanfile,
    HaxelibJson,
    TerraformTf,
    HelmChartYaml,
    AnsibleGalaxyRequirementsYaml,
    BazelModule,
    NixFlake,
    UnityProjectManifestJson,
    CocoaPodsPodfile,
    NpmPackageJson,
    NpmPackageJson5,
    NpmPackageYaml,
    PnpmYaml,
    PythonPipfile,
    PythonPyprojectToml,
    PythonRequirementsTxt,
    PubspecOverridesYaml,
    PubspecYaml,
    VersionLensMultiRegistries,
    Unknown,
}

const MANIFEST_ECOSYSTEMS: &[(ManifestKind, Ecosystem)] = &[
    (CargoToml, Cargo),
    (ComposerJson, Composer),
    (DenoJson, Deno),
    (DenoImportMapJson, Deno),
    (JsrJson, Deno),
    (DotnetProjectJson, Dotnet),
    (DotnetXml, Dotnet),
    (PaketDependencies, Dotnet),
    (PaketReferences, Dotnet),
    (DockerComposeYaml, Docker),
    (Dockerfile, Docker),
    (KustomizationYaml, Docker),
    (DubJson, Dub),
    (DubSdl, Dub),
    (Gemfile, Ruby),
    (RubyGemspec, Ruby),
    (GoMod, Go),
    (MavenPomXml, Maven),
    (GradleBuild, Maven),
    (GradleSettings, Maven),
    (GradleVersionCatalogToml, Maven),
    (SbtBuild, Maven),
    (ClojureDepsEdn, Maven),
    (LeiningenProjectClj, Maven),
    (MixExs, Hex),
    (RebarConfig, Hex),
    (GleamToml, Hex),
    (Opam, OpamEcosystem),
    (DuneProject, OpamEcosystem),
    (Cabal, Hackage),
    (CabalProject, Hackage),
    (StackYaml, Hackage),
    (JuliaProjectToml, Julia),
    (JuliaManifestToml, Julia),
    (RDescription, Cran),
    (RenvLock, Cran),
    (ConanfileTxt, Conan),
    (ConanfilePy, Conan),
    (VcpkgJson, Vcpkg),
    (Cmake, Cpp),
    (XmakeLua, Cpp),
    (MesonWrap, Cpp),
    (BazelWorkspace, Cpp),
    (SwiftPackage, Swift),
    (ZigBuildZon, Zig),
    (Nimble, Nim),
    (LuaRockspec, LuaRocks),
    (Cpanfile, Cpan),
    (HaxelibJson, Haxelib),
    (TerraformTf, Terraform),
    (HelmChartYaml, Helm),
    (AnsibleGalaxyRequirementsYaml, AnsibleGalaxy),
    (BazelModule, Bazel),
    (NixFlake, Nix),
    (UnityProjectManifestJson, Unity),
    (CocoaPodsPodfile, CocoaPods),
    (NpmPackageJson, Npm),
    (NpmPackageJson5, Npm),
    (NpmPackageYaml, Npm),
    (PnpmYaml, Npm),
    (PythonPipfile, Python),
    (PythonPyprojectToml, Python),
    (PythonRequirementsTxt, Python),
    (PubspecOverridesYaml, Pub),
    (PubspecYaml, Pub),
];

pub fn ecosystem_for_manifest(kind: ManifestKind) -> Option<Ecosystem> {
    MANIFEST_ECOSYSTEMS
        .iter()
        .find_map(|(candidate, ecosystem)| (*candidate == kind).then_some(*ecosystem))
}
