"Push to master trigger -> Run tests":
  stage: test
  variables:
    IS_TEST: "1"
  trigger:
    strategy: depend
    include:
      - local: build/build.gitlab-ci.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

"Merge to master trigger -> Run tests":
  stage: test
  variables:
    IS_TEST: "1"
  trigger:
    strategy: depend
    include:
      - local: build/build.gitlab-ci.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

"Generate package artifact trigger":
  stage: build
  variables:
    IS_PACKAGE: "1"
  trigger:
    strategy: depend
    include:
      - local: build/build.gitlab-ci.yml
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^\d+.\d+.\d+-[a-zA-Z]+.[0-9]+$/
    - when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

"Publish preview trigger":
  stage: deploy
  variables:
    IS_PREVIEW: "1"
  trigger:
    strategy: depend
    include:
      - local: build/build.gitlab-ci.yml
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^\d+.\d+.\d+-preview+$/
    - when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

publish_trigger:
  stage: deploy
  variables:
    IS_PUBLISH: "1"
  trigger:
    strategy: depend
    include:
      - local: build/build.gitlab-ci.yml
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/
    - when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH