import type { ConfigKeyPair } from "../key-pair.ts";

export const providerCacheKeys: readonly ConfigKeyPair[] = [
	["cargo", "cargo.caching.duration"],
	["composer", "composer.caching.duration"],
	["deno", "deno.caching.duration"],
	["docker", "docker.caching.duration"],
	["dotnet", "dotnet.caching.duration"],
	["dub", "dub.caching.duration"],
	["golang", "golang.caching.duration"],
	["maven", "maven.caching.duration"],
	["npm", "npm.caching.duration"],
	["pub", "pub.caching.duration"],
	["pypi", "pypi.caching.duration"],
	["ruby", "ruby.caching.duration"],
	["hex", "hex.caching.duration"],
	["opam", "opam.caching.duration"],
	["hackage", "hackage.caching.duration"],
	["julia", "julia.caching.duration"],
	["cran", "cran.caching.duration"],
	["conan", "conan.caching.duration"],
	["vcpkg", "vcpkg.caching.duration"],
	["swift", "swift.caching.duration"],
	["zig", "zig.caching.duration"],
	["nim", "nim.caching.duration"],
	["luarocks", "luarocks.caching.duration"],
	["cpan", "cpan.caching.duration"],
	["haxelib", "haxelib.caching.duration"],
	["terraform", "terraform.caching.duration"],
	["helm", "helm.caching.duration"],
	["ansible", "ansible.caching.duration"],
	["bazel", "bazel.caching.duration"],
	["nix", "nix.caching.duration"],
	["kustomize", "kustomize.caching.duration"],
	["unity", "unity.caching.duration"],
	["cocoapods", "cocoapods.caching.duration"],
] as const;
