import type { ConfigKeyPair } from "../key-pair.ts";

export const dependencyPropertyKeys: readonly ConfigKeyPair[] = [
	["cargo", "cargo.dependencyProperties"],
	["composer", "composer.dependencyProperties"],
	["deno", "deno.dependencyProperties"],
	["dotnet", "dotnet.dependencyProperties"],
	["dub", "dub.dependencyProperties"],
	["maven", "maven.dependencyProperties"],
	["npm", "npm.dependencyProperties"],
	["pnpm", "pnpm.dependencyProperties"],
	["pub", "pub.dependencyProperties"],
	["pypi", "pypi.dependencyProperties"],
	["hex", "hex.dependencyProperties"],
	["opam", "opam.dependencyProperties"],
	["hackage", "hackage.dependencyProperties"],
	["julia", "julia.dependencyProperties"],
	["cran", "cran.dependencyProperties"],
	["conan", "conan.dependencyProperties"],
	["vcpkg", "vcpkg.dependencyProperties"],
	["swift", "swift.dependencyProperties"],
	["zig", "zig.dependencyProperties"],
	["nim", "nim.dependencyProperties"],
	["luarocks", "luarocks.dependencyProperties"],
	["cpan", "cpan.dependencyProperties"],
	["haxelib", "haxelib.dependencyProperties"],
	["terraform", "terraform.dependencyProperties"],
	["helm", "helm.dependencyProperties"],
	["ansible", "ansible.dependencyProperties"],
	["bazel", "bazel.dependencyProperties"],
	["nix", "nix.dependencyProperties"],
	["kustomize", "kustomize.dependencyProperties"],
	["unity", "unity.dependencyProperties"],
	["cocoapods", "cocoapods.dependencyProperties"],
	["cpp", "cpp.dependencyProperties"],
] as const;
