import type { ConfigKeyPair } from "../key-pair.ts";

export const providerStrictSslKeys: readonly ConfigKeyPair[] = [
	["cargo", "cargo.http.strictSSL"],
	["composer", "composer.http.strictSSL"],
	["deno", "deno.http.strictSSL"],
	["docker", "docker.http.strictSSL"],
	["dotnet", "dotnet.http.strictSSL"],
	["dub", "dub.http.strictSSL"],
	["golang", "golang.http.strictSSL"],
	["maven", "maven.http.strictSSL"],
	["pub", "pub.http.strictSSL"],
	["pypi", "pypi.http.strictSSL"],
	["ruby", "ruby.http.strictSSL"],
	["hex", "hex.http.strictSSL"],
	["opam", "opam.http.strictSSL"],
	["hackage", "hackage.http.strictSSL"],
	["julia", "julia.http.strictSSL"],
	["cran", "cran.http.strictSSL"],
	["conan", "conan.http.strictSSL"],
	["vcpkg", "vcpkg.http.strictSSL"],
	["swift", "swift.http.strictSSL"],
	["zig", "zig.http.strictSSL"],
	["nim", "nim.http.strictSSL"],
	["luarocks", "luarocks.http.strictSSL"],
	["cpan", "cpan.http.strictSSL"],
	["haxelib", "haxelib.http.strictSSL"],
	["terraform", "terraform.http.strictSSL"],
	["helm", "helm.http.strictSSL"],
	["ansible", "ansible.http.strictSSL"],
	["bazel", "bazel.http.strictSSL"],
	["nix", "nix.http.strictSSL"],
	["kustomize", "kustomize.http.strictSSL"],
	["unity", "unity.http.strictSSL"],
	["cocoapods", "cocoapods.http.strictSSL"],
	["cpp", "cpp.http.strictSSL"],
] as const;
