import type { ConfigKeyPair } from "../key-pair.ts";

export const prereleaseTagKeys: readonly ConfigKeyPair[] = [
	["cargo", "cargo.prereleaseTagFilter"],
	["composer", "composer.prereleaseTagFilter"],
	["deno", "deno.prereleaseTagFilter"],
	["dotnet", "dotnet.prereleaseTagFilter"],
	["dub", "dub.prereleaseTagFilter"],
	["golang", "golang.prereleaseTagFilter"],
	["maven", "maven.prereleaseTagFilter"],
	["npm", "npm.prereleaseTagFilter"],
	["pypi", "pypi.prereleaseTagFilter"],
	["pub", "pub.prereleaseTagFilter"],
	["ruby", "ruby.prereleaseTagFilter"],
	["hex", "hex.prereleaseTagFilter"],
	["opam", "opam.prereleaseTagFilter"],
	["hackage", "hackage.prereleaseTagFilter"],
	["julia", "julia.prereleaseTagFilter"],
	["cran", "cran.prereleaseTagFilter"],
	["conan", "conan.prereleaseTagFilter"],
	["vcpkg", "vcpkg.prereleaseTagFilter"],
	["swift", "swift.prereleaseTagFilter"],
	["zig", "zig.prereleaseTagFilter"],
	["nim", "nim.prereleaseTagFilter"],
	["luarocks", "luarocks.prereleaseTagFilter"],
	["cpan", "cpan.prereleaseTagFilter"],
	["haxelib", "haxelib.prereleaseTagFilter"],
	["terraform", "terraform.prereleaseTagFilter"],
	["helm", "helm.prereleaseTagFilter"],
	["ansible", "ansible.prereleaseTagFilter"],
	["bazel", "bazel.prereleaseTagFilter"],
	["nix", "nix.prereleaseTagFilter"],
	["kustomize", "kustomize.prereleaseTagFilter"],
	["unity", "unity.prereleaseTagFilter"],
	["cocoapods", "cocoapods.prereleaseTagFilter"],
] as const;
