import type { ConfigKeyPair } from "../key-pair.ts";

export const registryUrlKeys: readonly ConfigKeyPair[] = [
	["cargo", "cargo.apiUrl"],
	["composer", "composer.apiUrl"],
	["dub", "dub.apiUrl"],
	["golang", "golang.apiUrl"],
	["maven", "maven.apiUrl"],
	["pypi", "pypi.apiUrl"],
	["pub", "pub.apiUrl"],
	["ruby", "ruby.apiUrl"],
	["hex", "hex.apiUrl"],
	["opam", "opam.apiUrl"],
	["hackage", "hackage.apiUrl"],
	["julia", "julia.apiUrl"],
	["cran", "cran.apiUrl"],
	["conan", "conan.apiUrl"],
	["vcpkg", "vcpkg.apiUrl"],
	["swift", "swift.apiUrl"],
	["zig", "zig.apiUrl"],
	["nim", "nim.apiUrl"],
	["luarocks", "luarocks.apiUrl"],
	["cpan", "cpan.apiUrl"],
	["haxelib", "haxelib.apiUrl"],
	["terraform", "terraform.apiUrl"],
	["helm", "helm.apiUrl"],
	["ansible", "ansible.apiUrl"],
	["bazel", "bazel.apiUrl"],
	["nix", "nix.apiUrl"],
	["unity", "unity.apiUrl"],
	["cocoapods", "cocoapods.apiUrl"],
	["cpp", "cpp.apiUrl"],
] as const;
