mod ansible;
mod bazel;
mod cargo;
mod cocoapods;
mod composer;
mod conan;
mod cpan;
mod cpp;
mod cran;
mod deno;
mod dub;
mod hackage;
mod haxelib;
mod helm;
mod hex;
mod julia;
mod luarocks;
mod nim;
mod nix;
mod npm;
mod opam;
mod pub_dev;
mod python;
mod ruby;
mod swift;
mod terraform;
mod unity;
mod vcpkg;
mod zig;

pub use ansible::ansible_role_registry_url_with_base;
pub(super) use ansible::{ansible_registry_url, ansible_registry_url_with_base};
pub(super) use bazel::{bazel_registry_url, bazel_registry_url_with_base};
pub(super) use cargo::{cargo_registry_url, cargo_registry_url_with_base};
pub(super) use cocoapods::{cocoapods_registry_url, cocoapods_registry_url_with_base};
pub(super) use composer::{composer_registry_url, composer_registry_url_with_base};
pub(super) use conan::{conan_registry_url, conan_registry_url_with_base};
pub(super) use cpan::{cpan_registry_url, cpan_registry_url_with_base};
pub(super) use cpp::{cpp_registry_url, cpp_registry_url_with_base};
pub(super) use cran::{cran_registry_url, cran_registry_url_with_base};
pub(super) use deno::{deno_registry_url, deno_registry_url_with_base};
pub(super) use dub::{dub_registry_url, dub_registry_url_with_base};
pub(super) use hackage::{hackage_registry_url, hackage_registry_url_with_base};
pub(super) use haxelib::{haxelib_registry_url, haxelib_registry_url_with_base};
pub(super) use helm::{helm_registry_url, helm_registry_url_with_base};
pub(super) use hex::{hex_registry_url, hex_registry_url_with_base};
pub(super) use julia::{julia_registry_url, julia_registry_url_with_base};
pub(super) use luarocks::{luarocks_registry_url, luarocks_registry_url_with_base};
pub(super) use nim::{nim_registry_url, nim_registry_url_with_base};
pub(super) use nix::{nix_registry_url, nix_registry_url_with_base};
pub(super) use npm::{npm_registry_url, npm_registry_url_with_base};
pub(super) use opam::{opam_registry_url, opam_registry_url_with_base};
pub(super) use pub_dev::{pub_registry_url, pub_registry_url_with_base};
pub use python::python_package_json_url_template;
pub(super) use python::{python_registry_url, python_registry_url_with_base};
pub(super) use ruby::{ruby_registry_url, ruby_registry_url_with_base};
pub(super) use swift::{swift_registry_url, swift_registry_url_with_base};
pub(super) use terraform::{terraform_registry_url, terraform_registry_url_with_base};
pub(super) use unity::{unity_registry_url, unity_registry_url_with_base};
pub(super) use vcpkg::{vcpkg_registry_url, vcpkg_registry_url_with_base};
pub(super) use zig::{zig_registry_url, zig_registry_url_with_base};
