# Gemfile for smoke testing
source 'https://rubygems.org'

gem 'rails', '7.0.4'
gem 'sqlite3', '~> 1.4'
gem 'puma', '>= 5.6.5'
gem 'bootsnap', '1.13.0'
gem 'sass-rails'
gem 'byebug', '11.1.3' # test comment
gem 'ffaker', '2.21.0'
gem 'rspec-rails', '~> 6.0.1'
gem 'not_found_gem', '9.9.9'
gem 'rails', git: "https://github.com/rails/rails.git"